apiVersion: v1
data:
  adminDisplayName: YWRtaW4=
  adminPassword: MTIz
  adminUsername: YWRtaW4=
  iv: OD1HeSQ4KXhLMV9dLSZPZA==
  key: YEgwOCg8aywvVXcjLmVHT1RAfTRuJnJGJ29TZnlGQSk=
kind: Secret
metadata:
  creationTimestamp: "2000-01-01T00:00:00Z"
  labels:
    higress.io/resource-definer: higress
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:adminDisplayName: {}
        f:adminPassword: {}
        f:adminUsername: {}
        f:iv: {}
        f:key: {}
      f:metadata:
        f:labels:
          .: {}
          f:higress.io/resource-definer: {}
    manager: Kubernetes Java Client
    operation: Update
    time: "2026-03-16T12:29:13Z"
  name: higress-console
  namespace: higress-system
  resourceVersion: "2"
type: Opaque
