apiVersion: v1
data:
  data: '{"name":"example","domains":[],"pathPredicate":{"matchType":"PRE","matchValue":"/","caseSensitive":false},"headerPredicates":[],"urlParamPredicates":[],"upstreams":[{"provider":"example","weight":100,"modelMapping":{"*":"真实的模型名"}}],"modelPredicates":[{"matchType":"EQUAL","matchValue":"插件端看到的模型名"}],"authConfig":{"enabled":false},"fallbackConfig":{"enabled":false}}'
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-17T07:41:54Z"
  labels:
    higress.io/config-map-type: ai-route
    higress.io/resource-definer: higress
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:data: {}
      f:metadata:
        f:labels:
          .: {}
          f:higress.io/config-map-type: {}
          f:higress.io/resource-definer: {}
    manager: Kubernetes Java Client
    operation: Update
    time: "2026-03-17T07:41:54Z"
  name: ai-route-example
  namespace: higress-system
  resourceVersion: "1"
