apiVersion: v1
data:
  root-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIF+zCCA+OgAwIBAgIUH34gKCEhJmYxH0P4mEVscw3XAWAwDQYJKoZIhvcNAQEL
    BQAwgYsxCzAJBgNVBAYTAkNOMREwDwYDVQQIDAhTaGFuZ2hhaTERMA8GA1UEBwwI
    U2hhbmdoYWkxEDAOBgNVBAoMB0hpZ3Jlc3MxEDAOBgNVBAsMB0dhdGV3YXkxEDAO
    BgNVBAMMB1Jvb3QgQ0ExIDAeBgkqhkiG9w0BCQEWEXJvb3RjYUBoaWdyZXNzLmlv
    MCAXDTI2MDMxODA3MTEzMFoYDzIxMjYwMjIyMDcxMTMwWjCBizELMAkGA1UEBhMC
    Q04xETAPBgNVBAgMCFNoYW5naGFpMREwDwYDVQQHDAhTaGFuZ2hhaTEQMA4GA1UE
    CgwHSGlncmVzczEQMA4GA1UECwwHR2F0ZXdheTEQMA4GA1UEAwwHUm9vdCBDQTEg
    MB4GCSqGSIb3DQEJARYRcm9vdGNhQGhpZ3Jlc3MuaW8wggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQCy6ZlEq0MPLiM+llBY0OaB9rbg7BVCw4Eqdzc6990O
    f1B0/18IXMUq+qTk2oxS8JpCYgbuuTWTDvCU/l0sw5BQ9dsWXiD5tPfXyjCNNpzR
    akiYc5BWHwn1y/odDvhz7qbZ1acVgxdShrDUTOhPlyw6bb6VmXCQN3b9Ie1tiMSb
    etjTmKXqFJGCMu1W1mZH1NBpBJeFW3sSmgRz4tA/m69AF9h7oDJHhK1ousfofDtQ
    fUV6hIC+MDQ4QjOLPZyJIznLktfNGBkChBj7o5ZqdiKGqSf7oNo3z+JmIf/lKD+Y
    hlwLaaVfc9lrwtD6rd2Rtl+POU5aGIpJA+963sHyQ6MUDJYg3ryb9uRMVvpjweiD
    kcq1n2HbzijTOmWIlKbSe+fF2Ox3HVewZLHh7ODN/lBEvyjHncqqQIdnVQfYqibV
    srlfyR5/UUK3GJyyyKW2IX9Pmd460vOIOAbR7LlCnC5zz9f8LiMPiU6NzZZCPu2G
    1C7tQSo/eQSqoFoqyErholYOlKW/4A255eW9V03i5dKTf1/ACH/OYWYuijAx2jf9
    1bU1Bxf1qvRmK+7AgByNswtb9EN1wgZKr8WJVvKWXjkxMZ9xG9g0lRUGwja8hPet
    xpEvYpjvdBe9BEympjx93Po2IfBINSwJEyzvh0DZQ0nWgzuntyp2nXTjT/kkT5WT
    /wIDAQABo1MwUTAdBgNVHQ4EFgQUd7rXO/mCjD05kEvJUSh850EooFEwHwYDVR0j
    BBgwFoAUd7rXO/mCjD05kEvJUSh850EooFEwDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAgEAbkZSnnDkaGZ9K/l/cZMfCL8kb/rEZ8Bnj4rVClVNsYj4
    JUux7DBpXe34y1xFXC9PN6aHuAX16O0O1KVDp8GQDJm1GC+O3oDAtAgckFX2VSP8
    YjYlg1vGQYIcqGpY8Ks4W9bX16fmIX8XgZ9NonCQwqoOA95fNgDLaxgfuXuwdf/O
    q9sINXt8hhpuq5MiIPd8VLmDg2kbucNI2KIQb8EEqkdyHZRwxibHcjJKojX4zjI5
    c4HgnSIAbhhR1stDv5qR+7sCSV0hG2JWRPyMWdPzucuvhc37GeH/DtcecKi2TMhv
    wxiK30BMDwY0C4oQb5q81DP0BKQqsFLez3rXikD98sHIdeIuibfgQWSNcv7CHG6I
    Wd8cutz+55lqiSwlOZ91cjPBCKOZG+OktzCS0xJ17FLG8fJ6sGOxEDNg3DxCPkko
    mQebJ+Uyl+CpXjpl5DVnhrb4BUxEJP1m5DlmE7NSVub6OAZEQmzUlVZ2swe1//eh
    nurE5NFYdpipZBrnelNqs+kPNggF50zSfNswggCgPKh1QN9cytYQruX+mqsdanoM
    ab10EwewQFrSVAOzgyNDO3qB6ohF9Q1TE89aCZHlP+8y/mtn6JO2srfHkRtzX7bN
    zE/DV9A397QWD9CfMWGYEcc9nC2dr4FcY3Ag3rNDazSQG8DR+65WQfV8jtyq3mA=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-16T12:29:04Z"
  labels:
    istio.io/config: "true"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:root-cert.pem: {}
      f:metadata:
        f:labels:
          .: {}
          f:istio.io/config: {}
    manager: pilot-discovery
    operation: Update
    time: "2026-03-18T07:11:36Z"
  name: higress-ca-root-cert
  namespace: higress-system
  resourceVersion: "7"
